name: Purge expired database records
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Send purge request
        run: |
          curl --request POST \
          --url '${{ secrets.URL }}/api/purge-expired' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
